name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libserialport-dev doxygen

      - name: Setup CMake
        uses: lukka/get-cmake@v3.23.0
        
      - name: Create build directory
        run: mkdir -p build
  
      - name: Configure CMake
        run: |
          cd build
          cmake ../clientSide

      - name: Build client using CMake
        run: |
          cd build
          cmake --build .

      - name: Generate client documentation
        run: |
          cd build
          cmake --build . --target doc

      - name: Upload client documentation
        uses: actions/upload-artifact@v4
        with:
          name: client-docs
          path: build/docs

      #- name: Run tests
      #  run: |
      #    TBD
        
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Install Arduino core for AVR boards
        run: arduino-cli core install arduino:avr

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Build Arduino sketch (Server)
        run: arduino-cli compile --fqbn arduino:avr:uno serverSide/serverSide.ino

      #dummy
      - name: Upload Arduino Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arduino-build
          path: serverSide/build/

      - name: Generate server documentation
        run: |
          mkdir -p serverSide/build
          cd serverSide/build
          cmake ..
          cmake --build . --target doc

      - name: Upload server documentation
        uses: actions/upload-artifact@v4
        with:
          name: server-docs
          path: serverSide/build/docs

      #- name: Run tests
      #  run: |
      #    TBD